
path: /home/xihelm/Documents/realsence_image_processing/data  # dataset root dir
train: train/imgs # train images (relative to 'path')
val: validation/imgs  # val images (relative to 'path')

# Classes
names:
  0: tennis_ball