
path: /home/xihelm/Documents/realsence_image_processing/data  # dataset root dir
train: images/train # train images (relative to 'path')
val: images/validation  # val images (relative to 'path')

# Classes
names:
  0: tennis_ball